In [1]:
import numpy as np 
import pandas as pd

# nayv byes on socia network data


In [2]:
df = pd.read_csv("Social_Network_Ads.csv" ,
                 usecols = ['Age' , 'EstimatedSalary' , 'Purchased'])

In [3]:
df.head(2)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [4]:
x = df.drop(columns = ['Purchased']) # indeoendent column
y = df['Purchased'] # dependent column

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=23)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()

In [9]:
x_train_new = sc.fit_transform(x_train)

In [15]:
x_test_new = sc.fit_transform(x_test)

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [17]:
classifier.fit(x_train_new , y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(x_test_new)

In [19]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cn = confusion_matrix(y_test , y_pred)

In [22]:
cn

array([[48,  2],
       [ 5, 25]])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(y_test , y_pred)

0.9125

# nayv byes covid toy¶

In [25]:
df = pd.read_csv("covid_toy.csv")

In [26]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
si = SimpleImputer()

In [29]:
df['fever'] = si.fit_transform(df[['fever']])

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
lb = LabelEncoder()

In [32]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [33]:
df.head(2)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1

In [34]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
sc = StandardScaler()

In [39]:
x_train_new = sc.fit_transform(x_train)

In [40]:
x_test_new = sc.transform(x_test)

In [41]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [42]:
classifier.fit(x_train_new , y_train)

GaussianNB()

In [43]:
y_pred = classifier.predict(x_test_new)

In [44]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0])

In [45]:
from sklearn.metrics import confusion_matrix

In [46]:
cn = confusion_matrix(y_test , y_pred)

In [47]:
cn

array([[8, 5],
       [3, 4]])

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_test , y_pred)

0.6